package app

// Multi-database dialect support: sqlite by default; with the SQL_DSN
// environment variable set, mysql / postgres is used.
//
// Why it isn't "just add an env var":
//   - Placeholders: sqlite/mysql use ?, postgres uses $1/$2 — affects every
//     query; handled by the central rebind rewrite.
//   - Table-creation DDL: AUTOINCREMENT / types / whether TEXT can be a
//     primary key differ across all three — handled by schema conversion.
//   - upsert: INSERT OR REPLACE (sqlite) / REPLACE INTO (mysql) /
//     ON CONFLICT (pg) — generated by upsert().
// Not one of the ~70 ? queries in the business code needs changing; all
// dialect differences converge in this file.

import (
	"database/sql"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
)

type dbDialect int

const (
	dialectSQLite dbDialect = iota
	dialectMySQL
	dialectPostgres
)

// curDialect is set once from SQL_DSN inside getDB(); read-only globally
// afterwards.
var curDialect = dialectSQLite

// detectDSN identifies the dialect from SQL_DSN, returning the database/sql
// driver name and connection string. Once SQL_DSN is set it must be
// mysql/pg (if empty we never get here and stay on sqlite). Unrecognized →
// exit directly.
func detectDSN(dsn string) (dbDialect, string, string) {
	low := strings.ToLower(strings.TrimSpace(dsn))
	switch {
	case strings.HasPrefix(low, "postgres://"), strings.HasPrefix(low, "postgresql://"):
		return dialectPostgres, "postgres", dsn // lib/pq takes URLs directly
	case strings.HasPrefix(low, "mysql://"):
		return dialectMySQL, "mysql", mysqlURLToDSN(dsn)
	case strings.Contains(dsn, "@tcp("):
		return dialectMySQL, "mysql", ensureMySQLParams(dsn) // native go-sql-driver DSN
	default:
		fmt.Fprintf(os.Stderr, "[db] cannot recognize the SQL_DSN dialect (must start with postgres:// or postgresql:// or mysql://,"+
			"or be go-sql-driver's user:pass@tcp(host:port)/db form): %s\n", dsn)
		os.Exit(1)
		return dialectSQLite, "", ""
	}
}

// mysqlURLToDSN converts mysql://user:pass@host:port/db?x=y into
// go-sql-driver's user:pass@tcp(host:port)/db?x=y.
func mysqlURLToDSN(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[db] mysql DSN parse failed: %v\n", err)
		os.Exit(1)
	}
	cred := ""
	if u.User != nil {
		cred = u.User.Username()
		if p, ok := u.User.Password(); ok {
			cred += ":" + p
		}
	}
	out := fmt.Sprintf("%s@tcp(%s)/%s", cred, u.Host, strings.TrimPrefix(u.Path, "/"))
	if u.RawQuery != "" {
		out += "?" + u.RawQuery
	}
	return ensureMySQLParams(out)
}

func ensureMySQLParams(dsn string) string {
	if !strings.Contains(dsn, "charset=") {
		if strings.Contains(dsn, "?") {
			dsn += "&charset=utf8mb4"
		} else {
			dsn += "?charset=utf8mb4"
		}
	}
	return dsn
}

// ── Placeholder shim: getDB() returns *dbx; business code keeps calling
// .Exec/.Query/.QueryRow/.Begin as usual ──────

type dbx struct{ raw *sql.DB }

func (d *dbx) Exec(q string, a ...any) (sql.Result, error) { return d.raw.Exec(rebind(q), a...) }
func (d *dbx) Query(q string, a ...any) (*sql.Rows, error) { return d.raw.Query(rebind(q), a...) }
func (d *dbx) QueryRow(q string, a ...any) *sql.Row        { return d.raw.QueryRow(rebind(q), a...) }
func (d *dbx) Begin() (*txx, error) {
	t, err := d.raw.Begin()
	if err != nil {
		return nil, err
	}
	return &txx{t}, nil
}

type txx struct{ raw *sql.Tx }

func (t *txx) Exec(q string, a ...any) (sql.Result, error) { return t.raw.Exec(rebind(q), a...) }
func (t *txx) Query(q string, a ...any) (*sql.Rows, error) { return t.raw.Query(rebind(q), a...) }
func (t *txx) QueryRow(q string, a ...any) *sql.Row        { return t.raw.QueryRow(rebind(q), a...) }
func (t *txx) Commit() error                               { return t.raw.Commit() }
func (t *txx) Rollback() error                             { return t.raw.Rollback() }

// rebind rewrites ? in order to $1,$2… (postgres only). None of our
// queries contain string literals with ?, so sequential replacement is
// safe.
func rebind(q string) string {
	if curDialect != dialectPostgres {
		return q
	}
	var b strings.Builder
	n := 0
	for i := 0; i < len(q); i++ {
		if q[i] == '?' {
			n++
			b.WriteByte('$')
			b.WriteString(strconv.Itoa(n))
		} else {
			b.WriteByte(q[i])
		}
	}
	return b.String()
}

// insertID executes an INSERT and returns the auto-increment primary key.
// pg (lib/pq) doesn't support LastInsertId, so RETURNING id is used
// instead. The query must not carry a trailing semicolon; the primary key
// column is fixed as id.
func insertID(query string, args ...any) (int64, error) {
	if curDialect == dialectPostgres {
		var id int64
		err := getDB().QueryRow(query+" RETURNING id", args...).Scan(&id)
		return id, err
	}
	res, err := getDB().Exec(query, args...)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// upsert generates a dialect-compatible "insert or overwrite by primary
// key" statement. cols is all columns (including the primary key); pk is
// the primary key column.
func upsert(table string, cols, pk []string) string {
	ph := "?" + strings.Repeat(",?", len(cols)-1)
	collist := strings.Join(cols, ", ")
	switch curDialect {
	case dialectMySQL:
		return fmt.Sprintf("REPLACE INTO %s(%s) VALUES(%s)", table, collist, ph)
	case dialectPostgres:
		pkset := map[string]bool{}
		for _, c := range pk {
			pkset[c] = true
		}
		var sets []string
		for _, c := range cols {
			if !pkset[c] {
				sets = append(sets, c+"=excluded."+c)
			}
		}
		return fmt.Sprintf("INSERT INTO %s(%s) VALUES(%s) ON CONFLICT(%s) DO UPDATE SET %s",
			table, collist, ph, strings.Join(pk, ","), strings.Join(sets, ", "))
	default: // sqlite
		return fmt.Sprintf("INSERT OR REPLACE INTO %s(%s) VALUES(%s)", table, collist, ph)
	}
}

// ── Schema conversion per dialect ────────────────────────────────────────────────

var (
	reAutoPK      = regexp.MustCompile(`INTEGER PRIMARY KEY AUTOINCREMENT`)
	reInteger     = regexp.MustCompile(`\bINTEGER\b`)
	reTextDefault = regexp.MustCompile(`TEXT NOT NULL DEFAULT ('[^']*')`)
	reModelText   = regexp.MustCompile(`model\s+TEXT NOT NULL`) // model is part of a composite primary key/index; mysql TEXT can't be a key
	reIdxIfExists = regexp.MustCompile(`(?i)CREATE INDEX IF NOT EXISTS`)
)

// schemaStatements converts the sqlite schema into the target dialect and
// splits it into individual statements (the mysql/pg drivers don't support
// multi-statement Exec by default).
func schemaStatements(d dbDialect) []string {
	s := schema
	switch d {
	case dialectMySQL:
		s = reAutoPK.ReplaceAllString(s, "BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY")
		// mysql TEXT can't directly be a primary key/index/carry DEFAULT;
		// short text columns become VARCHAR.
		s = strings.ReplaceAll(s, "TEXT PRIMARY KEY", "VARCHAR(255) PRIMARY KEY")
		s = reModelText.ReplaceAllString(s, "model VARCHAR(255) NOT NULL")
		s = reTextDefault.ReplaceAllString(s, "VARCHAR(512) NOT NULL DEFAULT $1")
		s = reInteger.ReplaceAllString(s, "BIGINT")
		s = reIdxIfExists.ReplaceAllString(s, "CREATE INDEX") // mysql doesn't support CREATE INDEX IF NOT EXISTS
	case dialectPostgres:
		s = reAutoPK.ReplaceAllString(s, "BIGSERIAL PRIMARY KEY")
		s = reInteger.ReplaceAllString(s, "BIGINT")
	}
	// First strip -- inline comments line by line, then split on ; :
	// comments can contain semicolons (e.g. cookie strings "k=v; k=v"), and
	// splitting directly would cut a statement in the middle of a comment.
	// This schema's string literals contain no --, so direct truncation is
	// safe.
	var clean strings.Builder
	for _, ln := range strings.Split(s, "\n") {
		if i := strings.Index(ln, "--"); i >= 0 {
			ln = ln[:i]
		}
		clean.WriteString(ln)
		clean.WriteByte('\n')
	}
	var out []string
	for _, part := range strings.Split(clean.String(), ";") {
		if stmt := strings.TrimSpace(part); stmt != "" {
			out = append(out, stmt)
		}
	}
	return out
}
